### ISSUE TITLE
Provide a parsing fallback for lightbulbs that are incorrectly announced as remote controls

### ISSUE THREAD

**Issue by CliffS** [AlCalzone/node-tradfri-client#67]
My code has been running fine for a while now but today I added a new bulb.  It's the first bulb I have added using a movement sensor rather than a remote, if that matters.

I was having trouble tracking this bulb and I finally noticed that this bulb is returning AccessoryType of zero (remote) rather than 2 (lightbulb).  I have tried factory-resetting the bulb and re-adding it into a group controlled by a remote but `on('device updated', =>)` still returns an Accessory with type zero.

Have you ever seen this before?  Do I perhaps have a faulty bulb?  The Android app sees it as a light bulb, FWIW.  Any ideas?

**Comment by AlCalzone** [comment]
I have seen reports of this before, I believe its a bug in the gateway firmware - here's an extensive thread with the same problem: https://github.com/ggravlingen/pytradfri/issues/135

Resetting the gateway and remote to factory defaults and re-pairing will probably help. 

If you like, we could also use this bulb to test a software-side fallback solution. In that case I'd need some debug output ("observeDevice > ...") and some patience from you.

**Comment by CliffS** [comment]
Happy to help.  What do you need me to do?

**Comment by AlCalzone** [comment]
Run your script with the `DEBUG` env var set, e.g. like this:
```bash
DEBUG=node-tradfri-client node yourscript.js
```
and post the lines containing `"observeDevice > ..."` for the lightbulb in question.

**Comment by CliffS** [comment]
OK. this is the initial output using the environment variable.  The bulb in question is named `Sauna Light`.

[house.log](https://github.com/AlCalzone/node-tradfri-client/files/1845236/house.log)

**Comment by AlCalzone** [comment]
Thanks! That looks good, the main difference is that key 5750 is 0 (for remote) instead of 2 (for light) and the light payload is contained in key 15009 (for sensor) instead of 3311 (for light).

I think I can just cross-reference the device identifier (`"TRADFRI bulb E27 WS opal 980lm"`) with a list of identifiers that are known to be lights and then parse the other key.

**Comment by CliffS** [comment]
If you'd like to give me a version with this code, I'd be happy to test it for you.

**Comment by AlCalzone** [comment]
coming right up ;)

**Comment by AlCalzone** [comment]
https://github.com/AlCalzone/node-tradfri-client/tarball/fix-67 should do it, as long as I didn't miss anything in my component tests.

**Comment by CliffS** [comment]
Interesting.  It is now reported as a bulb.  However it doesn't quite work as expected but this may be to do with the Android app.

The app always starts by showing it as off, regardless.  If I switch it on from the app, I do not get a `device updated` event, as expected, as it is already on.  If I switch it off from the app, I correctly get a `device updated` event showing it as now off.  Then I switch it on again and the app crashes with
`Segmentation fault (core dumped)`. 

I've attached the core file, in case it's any use to you.  I'm pretty sure it's not crashing in my code (famous last words).

[_usr_bin_sudo.0.crash.gz](https://github.com/AlCalzone/node-tradfri-client/files/1845403/_usr_bin_sudo.0.crash.gz)

**Comment by AlCalzone** [comment]
When you say the app crashes, do you mean your library or the android app? If it's the latter, the might not like how I tried to fix stuff. 

Do you have any way of logging the traffic from the android app to the gateway when switching the faulty bulb? I used to do that by running the IKEA app inside BlueStacks on my PC and then have Wireshark listening.

**Comment by AlCalzone** [comment]
But before you do, please test again with the most recent code.
I pushed another commit to the branch where I don't try to restore the faulty object when sending.

**Comment by CliffS** [comment]
> When you say the app crashes, do you mean your library or the android app?

My node program crashes.  I am running a program which uses https://github.com/CliffS/ikea-tradfri and I have `npm link`ed your `fix-67` branch in.

> But before you do, please test again with the most recent code.

It still crashes in the same way, I assume in C/C++ code as it dumps core.

> Do you have any way of logging the traffic from the android app to the gateway when switching the faulty bulb?

Not currently.  I'll need to find a way of doing the same thing as BlueStacks on Linux (or find a Windows machine).

Let me try switching the bulb using your code.  I'll let you know what happens.

**Comment by CliffS** [comment]
> Let me try switching the bulb using your code. I'll let you know what happens.

Exactly the same when switching via your code.  I'll get you some debugging.

**Comment by AlCalzone** [comment]
Hmm that's weird. The only C++ code involved is the one responsive for encryption. At that point the changes I've made should make no difference as everything is treated like a string.

**Comment by CliffS** [comment]
> I'll get you some debugging.

This is the full output from the `debug` module.  First it loads all the devices, then I turn the dodgy bulb on, then off at which point it SIGSEGVs,  To try to ensure it's not my environment, I precompiled the coffee scripts and ran with `node server.js`.

[debug.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1845562/debug.log.gz)

> When you npm link back to the master branch, does stuff work again?

I can't test it without major changes to my code.  My library sees it as a remote rather than a bulb and therefore doesn't allow me to turn it on and off.

What I can say for sure is that with both branches of `node-tradfri-client`, I get no problem is I use a real bulb rather than the broken one.

**Comment by AlCalzone** [comment]
So, I see this block twice:
```
2018-03-25T16:58:43.186Z node-tradfri-client [SILLY] IPSODevice: checking if name is required...
2018-03-25T16:58:43.187Z node-tradfri-client [SILLY] IPSODevice: checking if createdAt is required...
2018-03-25T16:58:43.187Z node-tradfri-client [SILLY] IPSODevice: checking if instanceId is required...
2018-03-25T16:58:43.188Z node-tradfri-client [SILLY] IPSODevice: checking if colorTemperature is required...
2018-03-25T16:58:43.188Z node-tradfri-client [SILLY] IPSODevice: checking if UNKNOWN1 is required...
2018-03-25T16:58:43.189Z node-tradfri-client [SILLY] IPSODevice: checking if onOff is required...
2018-03-25T16:58:43.190Z node-tradfri-client [SILLY] IPSODevice: checking if dimmer is required...
2018-03-25T16:58:43.190Z node-tradfri-client [SILLY] IPSODevice: checking if colorTemperature is always required...
```
The first time it has Light instead of IPSODevice and your code continues to run. At the end it has IPSODevice and crashes.

To better understand whats going on, I pushed two versions of the code:
https://github.com/AlCalzone/node-tradfri-client/tarball/4a4a2e and https://github.com/AlCalzone/node-tradfri-client/commit/db48654
Please test with both and provide me a log each.

**Comment by CliffS** [comment]
Actually it's much easier if you can give me a branch or commit than a tarball.

These are the two log files.  They are taken at the commits `find out what's going on (try 1)` (4a4a2ee349c37bc04ad1f75deba9d04b9a8dcace) and `find out what's going on (try 2)` (db48654ab13c174d7c27d44aa796e5a1de4ecaf4).

[debug-try1.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1845663/debug-try1.log.gz) and [debug-try2.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1845664/debug-try2.log.gz)

In each case, I turned on the light, turned it off and then on again at which point it SIGSEGV'd.

**Comment by AlCalzone** [comment]
> Actually it's much easier if you can give me a branch or commit than a tarball.

Ok I'll keep that in mind. I'll probably look at your logs tomorrow. Thanks!

**Comment by AlCalzone** [comment]
Next attempt: 72e9a3a
The usual please ;)

**Comment by CliffS** [comment]
>Next attempt: 72e9a3a
> The usual please ;)

Same issue.  SIGSEGV  [next-attempt.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1847342/next-attempt.log.gz)

Also tried the commit 669f59b26005e2fea756ad6200cb4ab578f36dbc [does-the-PR.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1847358/does-the-PR.log.gz) in case you'd made further changes.

FWIW, the only way I have ever managed to make Node SIGSEGV is to feed it invalid code.  My favourite is to forget to resolve a conflict when it crashes on the `>>>>>>>`.

**Comment by AlCalzone** [comment]
669f59b was just to diagnose something with CircleCI and Coveralls. As I'm probably going to squash the PR, I figured this is a good place for a throwaway commit.

I think I can rule out syntactically invalid code, VSCode and TypeScript would complain heavily if there was some. As I have all your logs now, I'm going to recreate your exact situation on my machine. 

In the meantime, could you try to include this into your program to try and get some more information on the segfault? https://github.com/ddopson/node-segfault-handler

**Comment by CliffS** [comment]
> In the meantime, could you try to include this into your program to try and get some more information on the segfault?

It didn't help very much, I'm afraid.  Just outputs `PID 15693 received SIGSEGV for address: 0x3`.

**Comment by AlCalzone** [comment]
Wow... that's helpful :D /s

The extended debug log is all we have then, I guess ;)

**Comment by CliffS** [comment]
I've just moved my code to my desktop machine (x86_64) from the Raspberry Pi (armv7l) it was running on.  I get a very different result.  It's throwing an exception inside my code now.  Give me a few minutes to dig deeper.

**Comment by CliffS** [comment]
OK, what seems to be happening is that sometimes your code returns type 0 and sometimes type 2.  This breaks my code which tries to update `type` which is held in a read-only property.  Not sure yet but  think it returns 0  when the bulb is off and 2 when the bulb is on.

**Comment by CliffS** [comment]
Not sure if this will help.  It is the raw output of the device as returned to me from the `device updated` event.  It was dumped with:

```javascript
        if (device.name == 'Sauna Light') {
          console.error('---------------------------------------------------');
          console.error(util.inspect(device, {depth: 4}));
        }
```

[devices.log.gz](https://github.com/AlCalzone/node-tradfri-client/files/1847874/devices.log.gz)

**Comment by CliffS** [comment]
The more I look at this, the more I think you should probably not be trying to fix Ikea's bugs in your software.  FWIW, the Android software sometimes crashes while it is watching the state of the bulb and doesn't track it correctly.  It also gets the state wrong.  Turning the bulb on or off via the Android app is not reflected in events in your code.

**Comment by AlCalzone** [comment]
Interesting: I can see no real difference between the first two and the third payload, but the third one doesn't get recognized as a "disguised" light. When I parse the same payload manually, it works.

Whatever, I'm inclined to drop this for the reason you mentioned.
